### ISSUE TITLE
Generate Scala implementation of the gRPC service

### ISSUE THREAD

**Issue by augi** [avast/cactus#36]
Use-case for the gRPC client:
1. User has the protofile.
2. User writes a `trait` that describes the service.
3. cactus provides method that could be called like this: `createClient[MyTrait](grpcJavaClientInstance)`
  * So the result is a adapter that allows to call Java API using Scala API. Maybe in the first iteration, it could be just about transforming to/from `Future`. Support for the case-classes mapping can be added later.

Use-case for the gRCP server:
1. User has the protofile.
2. User writes a `class` that has same methods as a gRPC service.
3. cactus ensure mapping between the generated server stub and the Scala implementation. It could be like `wrapAsGrpcService[GrpcServiceInterface](myImplementation)`. The mapping could be name-based.

**Comment by jendakol** [comment]
Solved in PR #38
